name: Default Node CI

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  lint:
    name: lints
    runs-on: ubuntu-latest
    steps:
      - name: Checking Out Commits Securely . . .
        uses: actions/checkout@v2
      - name: Setup Node 16 Environment . . .
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install Dependencies . . .
        working-directory: .
        run: npm ci
      - name: Build Docker Image "free-ignorance/fortunecookie"
        run: docker build -t free-ignorance/fortunecookie .
      - name: Run The Lints . . .
        run: docker run free-ignorance/fortunecookie npm run test:lint
  tests:
    name: tests
    runs-on: ubuntu-latest
    steps:
      - name: Checking Out Commits Securely . . .
        uses: actions/checkout@v2
      - name: Setup Node 16 Environment . . .
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install Dependencies . . .
        working-directory: .
        run: npm ci
      - name: Build Docker Image "free-ignorance/fortunecookie"
        run: docker build -t free-ignorance/fortunecookie .
      - name: Run The Tests . . .
        run: docker run free-ignorance/fortunecookie npm run test

  coverage:
    name: coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checking Out Commits Securely . . .
        uses: actions/checkout@v2
      - name: Setup Node 16 Environment . . .
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install Dependencies . . .
        working-directory: .
        run: npm ci
      - name: Run The Tests . . .
        run: npm run test --coverage --coverageDirectory=./coverage/reports/
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./coverage/reports/
          fail_ci_if_error: true
